set(CMAKE_SYSTEM_NAME Windows)
set(MSYS 1)
set(BUILD_SHARED_LIBS OFF)
set(CMAKE_BUILD_TYPE Release)
set(CMAKE_FIND_ROOT_PATH /Users/aaa/mxe/usr/i686-pc-mingw32)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_C_COMPILER /Users/aaa/mxe/usr/bin/i686-pc-mingw32-gcc)
set(CMAKE_CXX_COMPILER /Users/aaa/mxe/usr/bin/i686-pc-mingw32-g++)
set(CMAKE_Fortran_COMPILER /Users/aaa/mxe/usr/bin/i686-pc-mingw32-gfortran)
set(CMAKE_RC_COMPILER /Users/aaa/mxe/usr/bin/i686-pc-mingw32-windres)
set(HDF5_C_COMPILER_EXECUTABLE /Users/aaa/mxe/usr/bin/i686-pc-mingw32-h5cc)
set(HDF5_CXX_COMPILER_EXECUTABLE /Users/aaa/mxe/usr/bin/i686-pc-mingw32-h5c++)
set(PKG_CONFIG_EXECUTABLE /Users/aaa/mxe/usr/bin/i686-pc-mingw32-pkg-config)
set(QT_QMAKE_EXECUTABLE /Users/aaa/mxe/usr/i686-pc-mingw32/qt/bin/qmake)
set(CMAKE_INSTALL_PREFIX /Users/aaa/mxe/usr/i686-pc-mingw32 CACHE PATH "Installation Prefix")
set(CMAKE_BUILD_TYPE Release CACHE STRING "Debug|Release|RelWithDebInfo|MinSizeRel")
